# Classification Exercise

We'll be working with some California Census Data, we'll be trying to use various features of an individual to predict what class of income they belogn in (>50k or <=50k). 

Here is some information about the data:

<table>
<thead>
<tr>
<th>Column Name</th>
<th>Type</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td>age</td>
<td>Continuous</td>
<td>The age of the individual</td>
</tr>
<tr>
<td>workclass</td>
<td>Categorical</td>
<td>The type of employer the  individual has (government,  military, private, etc.).</td>
</tr>
<tr>
<td>fnlwgt</td>
<td>Continuous</td>
<td>The number of people the census  takers believe that observation  represents (sample weight). This  variable will not be used.</td>
</tr>
<tr>
<td>education</td>
<td>Categorical</td>
<td>The highest level of education  achieved for that individual.</td>
</tr>
<tr>
<td>education_num</td>
<td>Continuous</td>
<td>The highest level of education in  numerical form.</td>
</tr>
<tr>
<td>marital_status</td>
<td>Categorical</td>
<td>Marital status of the individual.</td>
</tr>
<tr>
<td>occupation</td>
<td>Categorical</td>
<td>The occupation of the individual.</td>
</tr>
<tr>
<td>relationship</td>
<td>Categorical</td>
<td>Wife, Own-child, Husband,  Not-in-family, Other-relative,  Unmarried.</td>
</tr>
<tr>
<td>race</td>
<td>Categorical</td>
<td>White, Asian-Pac-Islander,  Amer-Indian-Eskimo, Other, Black.</td>
</tr>
<tr>
<td>gender</td>
<td>Categorical</td>
<td>Female, Male.</td>
</tr>
<tr>
<td>capital_gain</td>
<td>Continuous</td>
<td>Capital gains recorded.</td>
</tr>
<tr>
<td>capital_loss</td>
<td>Continuous</td>
<td>Capital Losses recorded.</td>
</tr>
<tr>
<td>hours_per_week</td>
<td>Continuous</td>
<td>Hours worked per week.</td>
</tr>
<tr>
<td>native_country</td>
<td>Categorical</td>
<td>Country of origin of the  individual.</td>
</tr>
<tr>
<td>income</td>
<td>Categorical</td>
<td>"&gt;50K" or "&lt;=50K", meaning  whether the person makes more  than \$50,000 annually.</td>
</tr>
</tbody>
</table>

### THE DATA

** Read in the census_data.csv data with pandas**

In [1]:
import pandas as pd

In [2]:
my_data = pd.read_csv('census_data.csv')

In [4]:
my_data

,age,workclass,education,education_num,marital_status,occupation,relationship,race,gender,capital_gain,capital_loss,hours_per_week,native_country,income_bracket
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
10,37,Private,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
11,30,State-gov,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
12,23,Private,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
13,32,Private,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
14,40,Private,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K
15,34,Private,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
16,25,Self-emp-not-inc,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
17,32,Private,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
18,38,Private,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
19,43,Self-emp-not-inc,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
20,40,Private,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
21,54,Private,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
22,35,Federal-gov,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K
23,43,Private,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
24,59,Private,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
25,56,Local-gov,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
26,19,Private,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
27,54,?,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
28,39,Private,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
29,49,Private,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32531,30,?,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K
32532,34,Private,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
32533,54,Private,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,50,Japan,>50K
32534,37,Private,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,39,United-States,<=50K
32535,22,Private,12th,8,Never-married,Protective-serv,Own-child,Black,Male,0,0,35,United-States,<=50K
32536,34,Private,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,>50K
32537,30,Private,HS-grad,9,Never-married,Craft-repair,Not-in-family,Black,Male,0,0,46,United-States,<=50K
32538,38,Private,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,15020,0,45,United-States,>50K
32539,71,?,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K
32540,45,State-gov,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
32541,41,?,HS-grad,9,Separated,?,Not-in-family,Black,Female,0,0,32,United-States,<=50K
32542,72,?,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,25,United-States,<=50K
32543,45,Local-gov,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States,<=50K
32544,31,Private,Masters,14,Divorced,Other-service,Not-in-family,Other,Female,0,0,30,United-States,<=50K
32545,39,Local-gov,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K
32546,37,Private,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,<=50K
32547,43,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,Mexico,<=50K
32548,65,Self-emp-not-inc,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
32549,43,State-gov,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
32550,43,Self-emp-not-inc,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K
32551,32,Private,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K
32552,43,Private,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States,<=50K
32553,32,Private,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
32554,53,Private,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
32555,22,Private,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32556,27,Private,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

** TensorFlow won't be able to understand strings as labels, you'll need to use pandas .apply() method to apply a custom function that converts them to 0s and 1s. **

** Convert the Label column to 0s and 1s instead of strings.**

In [5]:
my_data['income_bracket'].unique()

array([' <=50K', ' >50K'], dtype=object)

In [6]:
def label_fix(label):
    if label == ' <=50K':
        return 0
    else:
        return 1

In [7]:
my_data['income_bracket'] = my_data['income_bracket'].apply(label_fix)

In [9]:
my_data.head()

,age,workclass,education,education_num,marital_status,occupation,relationship,race,gender,capital_gain,capital_loss,hours_per_week,native_country,income_bracket
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,0
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,0
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,0
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,0
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,0

### Perform a Train Test Split on the Data

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_data = my_data.drop('income_bracket', axis=1)

In [15]:
y_labels = my_data['income_bracket']

In [47]:
X_train, X_test, y_train, y_test = train_test_split(x_data, y_labels, test_size=0.33, random_state=101)

### Create the Feature Columns for tf.esitmator

** Take note of categorical vs continuous values! **

In [17]:
my_data.columns

Index(['age', 'workclass', 'education', 'education_num', 'marital_status',
       'occupation', 'relationship', 'race', 'gender', 'capital_gain',
       'capital_loss', 'hours_per_week', 'native_country', 'income_bracket'],
      dtype='object')

** Import Tensorflow **

In [19]:
import tensorflow as tf

** Create the tf.feature_columns for the categorical values. Use vocabulary lists or just use hash buckets. Use jash buckets when u dont know how many categori in this feature**

In [25]:
workclass = tf.feature_column.categorical_column_with_hash_bucket("workclass", hash_bucket_size=1000)

education = tf.feature_column.categorical_column_with_hash_bucket("education", hash_bucket_size=1000)

marital_status = tf.feature_column.categorical_column_with_hash_bucket("marital_status", hash_bucket_size=1000)

relationship = tf.feature_column.categorical_column_with_hash_bucket("relationship", hash_bucket_size=1000)

occupation = tf.feature_column.categorical_column_with_hash_bucket("occupation", hash_bucket_size=1000)

native_country = tf.feature_column.categorical_column_with_hash_bucket("native_country", hash_bucket_size=1000)

gender = tf.feature_column.categorical_column_with_vocabulary_list("gender", ['Female', 'Male'])

race = tf.feature_column.categorical_column_with_vocabulary_list("race", ['White', 'Black'])

** Create the continuous feature_columns for the continuous values using numeric_column **

In [24]:
age = tf.feature_column.numeric_column("age")

education_num = tf.feature_column.numeric_column('education_num')

capital_gain = tf.feature_column.numeric_column('capital_gain')

capital_loss = tf.feature_column.numeric_column('capital_loss')

hours_per_week = tf.feature_column.numeric_column('hours_per_week')

** Put all these variables into a single list with the variable name feat_cols **

### Create Input Function

** Batch_size is up to you. But do make sure to shuffle!**

In [31]:
input_func = tf.estimator.inputs.pandas_input_fn(x=X_train, y=y_train, batch_size=100, num_epochs=None, shuffle=True)

#### Create your model with tf.estimator

**Create a LinearClassifier.(If you want to use a DNNClassifier, keep in mind you'll need to create embedded columns out of the cateogrical feature that use strings.)**

In [28]:
embedded_workclass = tf.feature_column.embedding_column(workclass, dimension=1000)
embedded_education = tf.feature_column.embedding_column(education, dimension=1000)
embedded_marital_status= tf.feature_column.embedding_column(marital_status, dimension=1000)
embedded_relationship = tf.feature_column.embedding_column(relationship, dimension=1000)
embedded_occupation = tf.feature_column.embedding_column(occupation, dimension=1000)
embedded_native_country = tf.feature_column.embedding_column(native_country, dimension=1000)
embedded_gender = tf.feature_column.embedding_column(gender, dimension=2)
embedded_race = tf.feature_column.embedding_column(race, dimension=2)

In [30]:
feat_cols = [ embedded_workclass, embedded_education, embedded_marital_status, embedded_relationship, embedded_occupation, 
             embedded_native_country, embedded_gender, embedded_race, age, education_num, capital_gain, capital_loss, 
             hours_per_week ]

In [32]:
dnn_model = tf.estimator.DNNClassifier(hidden_units=[10,20,20,20,10], feature_columns=feat_cols, n_classes=2)

INFO:tensorflow:Using default config.
WARNING:tensorflow:Using temporary folder as model directory: C:\Users\ASUS\AppData\Local\Temp\tmpwlfzdfgu
INFO:tensorflow:Using config: {'_save_checkpoints_secs': 600, '_tf_random_seed': 1, '_session_config': None, '_save_summary_steps': 100, '_keep_checkpoint_every_n_hours': 10000, '_keep_checkpoint_max': 5, '_save_checkpoints_steps': None, '_log_step_count_steps': 100, '_model_dir': 'C:\\Users\\ASUS\\AppData\\Local\\Temp\\tmpwlfzdfgu'}

** Train your model on the data. **

In [33]:
dnn_model.train(input_fn=input_func, steps=10000)

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into C:\Users\ASUS\AppData\Local\Temp\tmpwlfzdfgu\model.ckpt.
INFO:tensorflow:loss = 88.541824, step = 1
INFO:tensorflow:global_step/sec: 67.6127
INFO:tensorflow:loss = 31.714577, step = 101 (1.478 sec)
INFO:tensorflow:global_step/sec: 69.5335
INFO:tensorflow:loss = 37.31665, step = 201 (1.437 sec)
INFO:tensorflow:global_step/sec: 71.0107
INFO:tensorflow:loss = 39.770103, step = 301 (1.408 sec)
INFO:tensorflow:global_step/sec: 71.0614
INFO:tensorflow:loss = 36.191322, step = 401 (1.408 sec)
INFO:tensorflow:global_step/sec: 70.068
INFO:tensorflow:loss = 37.30063, step = 501 (1.427 sec)
INFO:tensorflow:global_step/sec: 70.2152
INFO:tensorflow:loss = 36.769398, step = 601 (1.423 sec)
INFO:tensorflow:global_step/sec: 56.2983
INFO:tensorflow:loss = 31.218124, step = 701 (1.786 sec)
INFO:tensorflow:global_step/sec: 47.4735
INFO:tensorflow:loss = 33.45619, step = 801 (2.104 sec)
INFO:tensorflow:global_step/sec: 44.4865
INFO:tensorflow:loss = 39.185547, step = 901 (2.256 sec)
INFO:tensorflow:global_step/sec: 49.5327
INFO:tensorflow:loss = 32.992775, step = 1001 (2.004 sec)
INFO:tensorflow:global_step/sec: 62.5578
INFO:tensorflow:loss = 41.328415, step = 1101 (1.599 sec)
INFO:tensorflow:global_step/sec: 59.8205
INFO:tensorflow:loss = 32.076126, step = 1201 (1.671 sec)
INFO:tensorflow:global_step/sec: 63.2188
INFO:tensorflow:loss = 32.16967, step = 1301 (1.582 sec)
INFO:tensorflow:global_step/sec: 55.7264
INFO:tensorflow:loss = 36.538876, step = 1401 (1.795 sec)
INFO:tensorflow:global_step/sec: 67.3192
INFO:tensorflow:loss = 42.673294, step = 1501 (1.485 sec)
INFO:tensorflow:global_step/sec: 67.1939
INFO:tensorflow:loss = 37.161453, step = 1601 (1.487 sec)
INFO:tensorflow:global_step/sec: 66.8004
INFO:tensorflow:loss = 31.164204, step = 1701 (1.497 sec)
INFO:tensorflow:global_step/sec: 67.0236
INFO:tensorflow:loss = 34.917713, step = 1801 (1.493 sec)
INFO:tensorflow:global_step/sec: 62.2779
INFO:tensorflow:loss = 40.915344, step = 1901 (1.605 sec)
INFO:tensorflow:global_step/sec: 63.7427
INFO:tensorflow:loss = 37.626717, step = 2001 (1.569 sec)
INFO:tensorflow:global_step/sec: 67.1583
INFO:tensorflow:loss = 42.15183, step = 2101 (1.490 sec)
INFO:tensorflow:global_step/sec: 58.0923
INFO:tensorflow:loss = 36.32574, step = 2201 (1.721 sec)
INFO:tensorflow:global_step/sec: 53.1922
INFO:tensorflow:loss = 41.341408, step = 2301 (1.887 sec)
INFO:tensorflow:global_step/sec: 52.4959
INFO:tensorflow:loss = 39.138023, step = 2401 (1.898 sec)
INFO:tensorflow:global_step/sec: 55.8904
INFO:tensorflow:loss = 26.75844, step = 2501 (1.790 sec)
INFO:tensorflow:global_step/sec: 64.647
INFO:tensorflow:loss = 35.04448, step = 2601 (1.545 sec)
INFO:tensorflow:global_step/sec: 63.6214
INFO:tensorflow:loss = 28.511229, step = 2701 (1.573 sec)
INFO:tensorflow:global_step/sec: 65.3207
INFO:tensorflow:loss = 38.93061, step = 2801 (1.531 sec)
INFO:tensorflow:global_step/sec: 64.2327
INFO:tensorflow:loss = 31.432734, step = 2901 (1.558 sec)
INFO:tensorflow:global_step/sec: 65.3207
INFO:tensorflow:loss = 34.843857, step = 3001 (1.530 sec)
INFO:tensorflow:global_step/sec: 62.6671
INFO:tensorflow:loss = 25.838137, step = 3101 (1.596 sec)
INFO:tensorflow:global_step/sec: 67.5656
INFO:tensorflow:loss = 29.57378, step = 3201 (1.480 sec)
INFO:tensorflow:global_step/sec: 67.3387
INFO:tensorflow:loss = 31.645882, step = 3301 (1.489 sec)
INFO:tensorflow:global_step/sec: 58.8424
INFO:tensorflow:loss = 25.085207, step = 3401 (1.695 sec)
INFO:tensorflow:global_step/sec: 67.8859
INFO:tensorflow:loss = 37.115276, step = 3501 (1.472 sec)
INFO:tensorflow:global_step/sec: 58.126
INFO:tensorflow:loss = 32.528725, step = 3601 (1.720 sec)
INFO:tensorflow:global_step/sec: 67.2935
INFO:tensorflow:loss = 32.509327, step = 3701 (1.487 sec)
INFO:tensorflow:global_step/sec: 67.4746
INFO:tensorflow:loss = 32.580803, step = 3801 (1.483 sec)
INFO:tensorflow:global_step/sec: 66.8449
INFO:tensorflow:loss = 39.0979, step = 3901 (1.495 sec)
INFO:tensorflow:global_step/sec: 67.1133
INFO:tensorflow:loss = 39.470406, step = 4001 (1.490 sec)
INFO:tensorflow:global_step/sec: 67.5656
INFO:tensorflow:loss = 29.987116, step = 4101 (1.480 sec)
INFO:tensorflow:global_step/sec: 67.4294
INFO:tensorflow:loss = 31.156042, step = 4201 (1.482 sec)
INFO:tensorflow:global_step/sec: 67.4291
INFO:tensorflow:loss = 27.59389, step = 4301 (1.484 sec)
INFO:tensorflow:global_step/sec: 67.7025
INFO:tensorflow:loss = 28.700867, step = 4401 (1.477 sec)
INFO:tensorflow:global_step/sec: 67.5657
INFO:tensorflow:loss = 31.98995, step = 4501 (1.483 sec)
INFO:tensorflow:global_step/sec: 63.6214
INFO:tensorflow:loss = 35.24652, step = 4601 (1.568 sec)
INFO:tensorflow:global_step/sec: 65.0664
INFO:tensorflow:loss = 29.947607, step = 4701 (1.538 sec)
INFO:tensorflow:global_step/sec: 67.52
INFO:tensorflow:loss = 25.06414, step = 4801 (1.481 sec)
INFO:tensorflow:global_step/sec: 67.5202
INFO:tensorflow:loss = 38.82323, step = 4901 (1.481 sec)
INFO:tensorflow:global_step/sec: 67.2484
INFO:tensorflow:loss = 31.601597, step = 5001 (1.487 sec)
INFO:tensorflow:global_step/sec: 63.7427
INFO:tensorflow:loss = 24.14933, step = 5101 (1.568 sec)
INFO:tensorflow:global_step/sec: 67.6111
INFO:tensorflow:loss = 34.251373, step = 5201 (1.480 sec)
INFO:tensorflow:global_step/sec: 60.2569
INFO:tensorflow:loss = 28.092268, step = 5301 (1.659 sec)
INFO:tensorflow:global_step/sec: 56.8731
INFO:tensorflow:loss = 33.251827, step = 5401 (1.760 sec)
INFO:tensorflow:global_step/sec: 64.4808
INFO:tensorflow:loss = 34.020157, step = 5501 (1.549 sec)
INFO:tensorflow:global_step/sec: 63.9866
INFO:tensorflow:loss = 38.175697, step = 5601 (1.564 sec)
INFO:tensorflow:global_step/sec: 64.8561
INFO:tensorflow:loss = 33.17818, step = 5701 (1.542 sec)
INFO:tensorflow:global_step/sec: 62.9424
INFO:tensorflow:loss = 24.496332, step = 5801 (1.589 sec)
INFO:tensorflow:global_step/sec: 63.4604
INFO:tensorflow:loss = 24.106056, step = 5901 (1.579 sec)
INFO:tensorflow:global_step/sec: 62.6671
INFO:tensorflow:loss = 23.488752, step = 6001 (1.592 sec)
INFO:tensorflow:global_step/sec: 59.9685
INFO:tensorflow:loss = 32.267395, step = 6101 (1.670 sec)
INFO:tensorflow:global_step/sec: 58.7734
INFO:tensorflow:loss = 28.970066, step = 6201 (1.700 sec)
INFO:tensorflow:global_step/sec: 63.2202
INFO:tensorflow:loss = 35.10041, step = 6301 (1.582 sec)
INFO:tensorflow:global_step/sec: 66.0959
INFO:tensorflow:loss = 38.712006, step = 6401 (1.514 sec)
INFO:tensorflow:global_step/sec: 66.934
INFO:tensorflow:loss = 30.661673, step = 6501 (1.493 sec)
INFO:tensorflow:global_step/sec: 66.4022
INFO:tensorflow:loss = 38.66033, step = 6601 (1.507 sec)
INFO:tensorflow:global_step/sec: 58.2272
INFO:tensorflow:loss = 24.393204, step = 6701 (1.716 sec)
INFO:tensorflow:global_step/sec: 62.0083
INFO:tensorflow:loss = 36.42099, step = 6801 (1.614 sec)
INFO:tensorflow:global_step/sec: 56.97
INFO:tensorflow:loss = 31.673847, step = 6901 (1.755 sec)
INFO:tensorflow:global_step/sec: 62.9031
INFO:tensorflow:loss = 23.206375, step = 7001 (1.588 sec)
INFO:tensorflow:global_step/sec: 61.5514
INFO:tensorflow:loss = 37.960888, step = 7101 (1.629 sec)
INFO:tensorflow:global_step/sec: 61.9699
INFO:tensorflow:loss = 21.147121, step = 7201 (1.611 sec)
INFO:tensorflow:global_step/sec: 49.7604
INFO:tensorflow:loss = 21.320778, step = 7301 (2.012 sec)
INFO:tensorflow:global_step/sec: 49.1556
INFO:tensorflow:loss = 41.714127, step = 7401 (2.033 sec)
INFO:tensorflow:global_step/sec: 50.5096
INFO:tensorflow:loss = 31.989315, step = 7501 (1.980 sec)
INFO:tensorflow:global_step/sec: 50.144
INFO:tensorflow:loss = 35.024048, step = 7601 (1.995 sec)
INFO:tensorflow:global_step/sec: 51.3414
INFO:tensorflow:loss = 27.103115, step = 7701 (1.946 sec)
INFO:tensorflow:global_step/sec: 61.6839
INFO:tensorflow:loss = 23.39655, step = 7801 (1.621 sec)
INFO:tensorflow:global_step/sec: 58.1354
INFO:tensorflow:loss = 38.94416, step = 7901 (1.720 sec)
INFO:tensorflow:global_step/sec: 62.6861
INFO:tensorflow:loss = 29.83126, step = 8001 (1.596 sec)
INFO:tensorflow:global_step/sec: 65.76
INFO:tensorflow:loss = 26.113167, step = 8101 (1.520 sec)
INFO:tensorflow:global_step/sec: 64.8231

INFO:tensorflow:loss = 25.256592, step = 8201 (1.544 sec)
INFO:tensorflow:global_step/sec: 62.8245
INFO:tensorflow:loss = 28.459045, step = 8301 (1.592 sec)
INFO:tensorflow:global_step/sec: 60.4384
INFO:tensorflow:loss = 28.345217, step = 8401 (1.654 sec)
INFO:tensorflow:global_step/sec: 66.8449
INFO:tensorflow:loss = 35.629772, step = 8501 (1.496 sec)
INFO:tensorflow:global_step/sec: 66.4462
INFO:tensorflow:loss = 29.086517, step = 8601 (1.505 sec)
INFO:tensorflow:global_step/sec: 67.2482
INFO:tensorflow:loss = 44.17704, step = 8701 (1.488 sec)
INFO:tensorflow:global_step/sec: 63.9869
INFO:tensorflow:loss = 29.81173, step = 8801 (1.563 sec)
INFO:tensorflow:global_step/sec: 64.3978
INFO:tensorflow:loss = 26.56762, step = 8901 (1.552 sec)
INFO:tensorflow:global_step/sec: 64.5636
INFO:tensorflow:loss = 27.960775, step = 9001 (1.548 sec)
INFO:tensorflow:global_step/sec: 66.9341
INFO:tensorflow:loss = 28.420431, step = 9101 (1.496 sec)
INFO:tensorflow:global_step/sec: 64.274
INFO:tensorflow:loss = 25.847008, step = 9201 (1.557 sec)
INFO:tensorflow:global_step/sec: 62.5889
INFO:tensorflow:loss = 26.144146, step = 9301 (1.597 sec)
INFO:tensorflow:global_step/sec: 59.5412
INFO:tensorflow:loss = 33.25553, step = 9401 (1.680 sec)
INFO:tensorflow:global_step/sec: 63.1804
INFO:tensorflow:loss = 35.117798, step = 9501 (1.583 sec)
INFO:tensorflow:global_step/sec: 56.2667
INFO:tensorflow:loss = 30.218079, step = 9601 (1.777 sec)
INFO:tensorflow:global_step/sec: 53.6822
INFO:tensorflow:loss = 24.563707, step = 9701 (1.863 sec)
INFO:tensorflow:global_step/sec: 63.8238
INFO:tensorflow:loss = 24.137548, step = 9801 (1.567 sec)
INFO:tensorflow:global_step/sec: 63.3001
INFO:tensorflow:loss = 31.836336, step = 9901 (1.580 sec)
INFO:tensorflow:Saving checkpoints for 10000 into C:\Users\ASUS\AppData\Local\Temp\tmpwlfzdfgu\model.ckpt.
INFO:tensorflow:Loss for final step: 36.519592.

### Evaluation

In [35]:
eval_input_func = tf.estimator.inputs.pandas_input_fn(X_test, y_test, batch_size=100, num_epochs=1, shuffle=False)

In [36]:
dnn_model.evaluate(eval_input_func)

WARNING:tensorflow:Casting <dtype: 'float32'> labels to bool.
WARNING:tensorflow:Casting <dtype: 'float32'> labels to bool.
INFO:tensorflow:Starting evaluation at 2021-08-03-16:39:23
INFO:tensorflow:Restoring parameters from C:\Users\ASUS\AppData\Local\Temp\tmpwlfzdfgu\model.ckpt-10000
INFO:tensorflow:Finished evaluation at 2021-08-03-16:39:25
INFO:tensorflow:Saving dict for global step 10000: accuracy = 0.855295, accuracy_baseline = 0.75944537, auc = 0.9110974, auc_precision_recall = 0.7880694, average_loss = 0.31106445, global_step = 10000, label/mean = 0.24055463, loss = 30.950912, prediction/mean = 0.23857056

{'accuracy': 0.855295,
 'accuracy_baseline': 0.75944537,
 'auc': 0.9110974,
 'auc_precision_recall': 0.7880694,
 'average_loss': 0.31106445,
 'global_step': 10000,
 'label/mean': 0.24055463,
 'loss': 30.950912,
 'prediction/mean': 0.23857056}

** Use model.predict() and pass in your input function. This will produce a generator of predictions, which you can then transform into a list, with list() **

In [51]:
pred_func = tf.estimator.inputs.pandas_input_fn(x=X_test, batch_size=len(X_test), shuffle=False)

In [52]:
pred_gen = dnn_model.predict(input_fn=pred_func)

In [53]:
predictions = list(pred_gen)

INFO:tensorflow:Restoring parameters from C:\Users\ASUS\AppData\Local\Temp\tmpwlfzdfgu\model.ckpt-10000

In [56]:
final_preds = [pred['class_ids'][0] for pred in predictions]

In [58]:
#final_preds

** Import classification_report from sklearn.metrics and then see if you can figure out how to use it to easily get a full report of your model's performance on the test data. **

In [59]:
from sklearn.metrics import classification_report

In [60]:
print(classification_report(y_test, final_preds))

              precision    recall  f1-score   support

           0       0.88      0.93      0.91      8161
           1       0.74      0.61      0.67      2585

    accuracy                           0.86     10746
   macro avg       0.81      0.77      0.79     10746
weighted avg       0.85      0.86      0.85     10746